name: 4xmssim_span_pretrain
model_type: default
scale: 4
use_amp: flase
bfloat16: false
fast_matmul: false
compile: false

datasets:
  train:
    type: paired
    dataroot_gt: '/home/phhofm/Documents/datasets/nomos_uni_gt/'
    dataroot_lq: '/home/phhofm/Documents/datasets/nomos_uni_lr_x4/'
    io_backend:
      type: disk

    gt_size: 128
    batch_size: 12
    accumulate: 1
    dataset_enlarge_ratio: 1

    use_hflip: true
    use_rot: true
    augmentation: ['none', 'mixup', 'cutmix', 'resizemix']
    aug_prob: [0.2, 0.3, 0.2, 0.5]

  val:
    name: val_1
    type: single
    dataroot_lq: '/home/phhofm/Downloads/helaman_testset_input/'
    io_backend:
      type: disk
val:
  val_freq: 5000
  save_img: true

path:
  # no pretrain
  resume_state: ~
  #strict_load_g: false # do not uncomment, read docs

network_g:
  type: span

train:
  optim_g:
    type: nadam
    lr: !!float 5e-4
    betas: [0.98, 0.99]
    weight_decay: 0.01
    decoupled_weight_decay: true

  scheduler:
    type: cosineannealing
    T_max: 350000
    eta_min: !!float 4e-5

  total_iter: 500000
  warmup_iter: -1 # no warmup

  # losses
  wavelet_guided: false
  #pixel_opt:
  #  type: L1Loss
  #  loss_weight: 1.0
  mssim_opt:
    type: mssim
    loss_weight: 1.0

  match_lq: false

logger:
  print_freq: 5000
  save_checkpoint_freq: 5000
  use_tb_logger: true
